# Generated by Django 5.1.2 on 2024-11-05 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorInfo',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('auth_birth', models.DateField()),
                ('auth_phonenum', models.BigIntegerField()),
                ('auth_address', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Publish',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('pub_name', models.CharField(max_length=16)),
                ('pub_address', models.CharField(max_length=16)),
                ('pub_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='电子邮箱')),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('auth_name', models.CharField(max_length=16)),
                ('auth_age', models.IntegerField(max_length=16)),
                ('author_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app20241105.authorinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('book_name', models.CharField(max_length=32)),
                ('book_pub_date', models.DateField()),
                ('book_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('authors', models.ManyToManyField(to='app20241105.author')),
                ('publish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app20241105.publish')),
            ],
        ),
    ]
