# Generated by Django 5.1.2 on 2024-11-05 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app20241105', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='auth_age',
            field=models.IntegerField(),
        ),
    ]
