# Generated by Django 5.1.2 on 2024-10-31 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app241030', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
